"""Constants exposed to AIs (Python equivalent of Java FightConstants)."""

from .effect.effect import Effect
from .attack.entity_state import EntityState
from .attack.attack import Attack
from .state.entity import Entity
from .fight.fight import Fight
from .state.state import State


MAX_TURNS = Fight.MAX_TURNS

CELL_EMPTY = 0
CELL_PLAYER = 1
CELL_ENTITY = 1
CELL_OBSTACLE = 2

# Entity types
ENTITY_LEEK = 1
ENTITY_BULB = 2
ENTITY_TURRET = 3
ENTITY_CHEST = 4
ENTITY_MOB = 5

# Bulb types
BULB_PUNY = 1
BULB_FIRE = 2
BULB_HEALER = 3
BULB_ROCKY = 4
BULB_ICED = 5
BULB_LIGHTNING = 6
BULB_METALLIC = 7
BULB_WIZARD = 8
BULB_TACTICIAN = 11
BULB_SAVANT = 12

# Constants
EFFECT_TARGET_ALLIES = Effect.TARGET_ALLIES
EFFECT_TARGET_ENEMIES = Effect.TARGET_ENEMIES
EFFECT_TARGET_CASTER = Effect.TARGET_CASTER
EFFECT_TARGET_NOT_CASTER = 0
EFFECT_TARGET_NON_SUMMONS = Effect.TARGET_NON_SUMMONS
EFFECT_TARGET_SUMMONS = Effect.TARGET_SUMMONS
EFFECT_TARGET_ALWAYS_CASTER = 0

# Effect modifiers
EFFECT_MODIFIER_STACKABLE = Effect.MODIFIER_STACKABLE
EFFECT_MODIFIER_MULTIPLIED_BY_TARGETS = Effect.MODIFIER_MULTIPLIED_BY_TARGETS
EFFECT_MODIFIER_ON_CASTER = Effect.MODIFIER_ON_CASTER
EFFECT_MODIFIER_NOT_REPLACEABLE = Effect.MODIFIER_NOT_REPLACEABLE
EFFECT_MODIFIER_IRREDUCTIBLE = Effect.MODIFIER_IRREDUCTIBLE

# Effect types
EFFECT_DAMAGE = 1
EFFECT_HEAL = 2
EFFECT_FORCE = 3
EFFECT_AGILITY = 4
EFFECT_RELATIVE_SHIELD = 5
EFFECT_ABSOLUTE_SHIELD = 6
EFFECT_MP = 7
EFFECT_TP = 8
EFFECT_TELEPORT = 10
EFFECT_INVERT = Effect.TYPE_PERMUTATION
EFFECT_RESURRECT = Effect.TYPE_RESURRECT
EFFECT_BUFF_DAMAGE = 1
EFFECT_BUFF_HEAL = 2
EFFECT_BUFF_FORCE = 3
EFFECT_BUFF_STRENGTH = 3
EFFECT_BUFF_AGILITY = 4
EFFECT_BUFF_RELATIVE_SHIELD = 5
EFFECT_BUFF_ABSOLUTE_SHIELD = 6
EFFECT_BUFF_MP = 7
EFFECT_BUFF_TP = 8
EFFECT_BUFF_DEBUFF = 9
EFFECT_BUFF_TELEPORTATION = 10
EFFECT_BOOST_MAX_LIFE = Effect.TYPE_VITALITY
EFFECT_POISON = Effect.TYPE_POISON
EFFECT_SUMMON = Effect.TYPE_SUMMON
EFFECT_DEBUFF = Effect.TYPE_DEBUFF
EFFECT_KILL = Effect.TYPE_KILL
EFFECT_SHACKLE_MP = Effect.TYPE_SHACKLE_MP
EFFECT_SHACKLE_TP = Effect.TYPE_SHACKLE_TP
EFFECT_SHACKLE_STRENGTH = Effect.TYPE_SHACKLE_STRENGTH
EFFECT_DAMAGE_RETURN = Effect.TYPE_DAMAGE_RETURN
EFFECT_BUFF_RESISTANCE = Effect.TYPE_BUFF_RESISTANCE
EFFECT_BUFF_WISDOM = Effect.TYPE_BUFF_WISDOM
EFFECT_SHACKLE_MAGIC = Effect.TYPE_SHACKLE_MAGIC
EFFECT_ANTIDOTE = Effect.TYPE_ANTIDOTE
EFFECT_AFTEREFFECT = Effect.TYPE_AFTEREFFECT
EFFECT_VULNERABILITY = Effect.TYPE_VULNERABILITY
EFFECT_ABSOLUTE_VULNERABILITY = Effect.TYPE_ABSOLUTE_VULNERABILITY
EFFECT_LIFE_DAMAGE = Effect.TYPE_LIFE_DAMAGE
EFFECT_STEAL_ABSOLUTE_SHIELD = Effect.TYPE_STEAL_ABSOLUTE_SHIELD
EFFECT_NOVA_DAMAGE = Effect.TYPE_NOVA_DAMAGE
EFFECT_RAW_BUFF_MP = Effect.TYPE_RAW_BUFF_MP
EFFECT_RAW_BUFF_TP = Effect.TYPE_RAW_BUFF_TP
EFFECT_POISON_TO_SCIENCE = Effect.TYPE_POISON_TO_SCIENCE
EFFECT_DAMAGE_TO_ABSOLUTE_SHIELD = Effect.TYPE_DAMAGE_TO_ABSOLUTE_SHIELD
EFFECT_DAMAGE_TO_STRENGTH = Effect.TYPE_DAMAGE_TO_STRENGTH
EFFECT_NOVA_DAMAGE_TO_MAGIC = Effect.TYPE_NOVA_DAMAGE_TO_MAGIC
EFFECT_RAW_ABSOLUTE_SHIELD = Effect.TYPE_RAW_ABSOLUTE_SHIELD
EFFECT_RAW_BUFF_STRENGTH = Effect.TYPE_RAW_BUFF_STRENGTH
EFFECT_RAW_BUFF_MAGIC = Effect.TYPE_RAW_BUFF_MAGIC
EFFECT_RAW_BUFF_SCIENCE = Effect.TYPE_RAW_BUFF_SCIENCE
EFFECT_RAW_BUFF_AGILITY = Effect.TYPE_RAW_BUFF_AGILITY
EFFECT_RAW_BUFF_RESISTANCE = Effect.TYPE_RAW_BUFF_RESISTANCE
EFFECT_PROPAGATION = Effect.TYPE_PROPAGATION
EFFECT_RAW_BUFF_WISDOM = Effect.TYPE_RAW_BUFF_WISDOM
EFFECT_NOVA_VITALITY = Effect.TYPE_NOVA_VITALITY
EFFECT_SLIDE_TO = Effect.TYPE_ATTRACT
EFFECT_ATTRACT = Effect.TYPE_ATTRACT
EFFECT_SHACKLE_AGILITY = Effect.TYPE_SHACKLE_AGILITY
EFFECT_SHACKLE_WISDOM = Effect.TYPE_SHACKLE_WISDOM
EFFECT_REMOVE_SHACKLES = Effect.TYPE_REMOVE_SHACKLES
EFFECT_MOVED_TO_MP = Effect.TYPE_MOVED_TO_MP
EFFECT_PUSH = Effect.TYPE_PUSH
EFFECT_RAW_BUFF_POWER = Effect.TYPE_RAW_BUFF_POWER
EFFECT_REPEL = Effect.TYPE_REPEL
EFFECT_RAW_RELATIVE_SHIELD = Effect.TYPE_RAW_RELATIVE_SHIELD
EFFECT_ALLY_KILLED_TO_AGILITY = Effect.TYPE_ALLY_KILLED_TO_AGILITY
EFFECT_KILL_TO_TP = Effect.TYPE_KILL_TO_TP
EFFECT_RAW_HEAL = Effect.TYPE_RAW_HEAL
EFFECT_CRITICAL_TO_HEAL = Effect.TYPE_CRITICAL_TO_HEAL
EFFECT_ADD_STATE = Effect.TYPE_ADD_STATE
EFFECT_TOTAL_DEBUFF = Effect.TYPE_TOTAL_DEBUFF
EFFECT_STEAL_LIFE = Effect.TYPE_STEAL_LIFE

# States
STATE_UNHEALABLE = EntityState.UNHEALABLE.value
STATE_INVINCIBLE = EntityState.INVINCIBLE.value

# Use results
USE_CRITICAL = 2
USE_SUCCESS = 1
USE_FAILED = 0
USE_INVALID_TARGET = -1
USE_NOT_ENOUGH_TP = -2
USE_INVALID_COOLDOWN = -3
USE_INVALID_POSITION = -4
USE_TOO_MUCH_SUMMONS = -5
USE_TOO_MANY_SUMMONS = -5
USE_RESURRECT_INVALID_ENTITY = -6
USE_MAX_USES = -7

# Areas
AREA_POINT = 1
AREA_LASER_LINE = 2
AREA_CIRCLE_1 = 3
AREA_CIRCLE_2 = 4
AREA_CIRCLE_3 = 5
AREA_PLUS_1 = 3
AREA_PLUS_2 = 6
AREA_PLUS_3 = 7
AREA_X_1 = 8
AREA_X_2 = 9
AREA_X_3 = 10
AREA_SQUARE_1 = 11
AREA_SQUARE_2 = 12
AREA_FIRST_INLINE = 13
AREA_ENEMIES = 14
AREA_ALLIES = 15

# Launch types
LAUNCH_TYPE_LINE = Attack.LAUNCH_TYPE_LINE
LAUNCH_TYPE_DIAGONAL = Attack.LAUNCH_TYPE_DIAGONAL
LAUNCH_TYPE_STAR = Attack.LAUNCH_TYPE_STAR
LAUNCH_TYPE_STAR_INVERTED = Attack.LAUNCH_TYPE_STAR_INVERTED
LAUNCH_TYPE_DIAGONAL_INVERTED = Attack.LAUNCH_TYPE_DIAGONAL_INVERTED
LAUNCH_TYPE_LINE_INVERTED = Attack.LAUNCH_TYPE_LINE_INVERTED
LAUNCH_TYPE_CIRCLE = Attack.LAUNCH_TYPE_CIRCLE

FIGHT_TYPE_SOLO = Fight.TYPE_SOLO
FIGHT_TYPE_FARMER = Fight.TYPE_FARMER
FIGHT_TYPE_TEAM = Fight.TYPE_TEAM
FIGHT_TYPE_BATTLE_ROYALE = Fight.TYPE_BATTLE_ROYALE
FIGHT_TYPE_BOSS = Fight.TYPE_BOSS
FIGHT_TYPE_WAR = Fight.TYPE_WAR
FIGHT_TYPE_CHEST_HUNT = Fight.TYPE_CHEST_HUNT
FIGHT_TYPE_COLOSSUS = Fight.TYPE_COLOSSUS

FIGHT_CONTEXT_TEST = Fight.CONTEXT_TEST
FIGHT_CONTEXT_GARDEN = Fight.CONTEXT_GARDEN
FIGHT_CONTEXT_CHALLENGE = Fight.CONTEXT_CHALLENGE
FIGHT_CONTEXT_TOURNAMENT = Fight.CONTEXT_TOURNAMENT
FIGHT_CONTEXT_BATTLE_ROYALE = Fight.CONTEXT_BATTLE_ROYALE

SUMMON_LIMIT = State.SUMMON_LIMIT
CRITICAL_FACTOR = Effect.CRITICAL_FACTOR
EROSION_DAMAGE = Effect.EROSION_DAMAGE
EROSION_POISON = Effect.EROSION_POISON
EROSION_CRITICAL_BONUS = Effect.EROSION_CRITICAL_BONUS

# Stats
STAT_LIFE = Entity.STAT_LIFE
STAT_TP = Entity.STAT_TP
STAT_MP = Entity.STAT_MP
STAT_STRENGTH = Entity.STAT_STRENGTH
STAT_AGILITY = Entity.STAT_AGILITY
STAT_FREQUENCY = Entity.STAT_FREQUENCY
STAT_WISDOM = Entity.STAT_WISDOM
STAT_ABSOLUTE_SHIELD = Entity.STAT_ABSOLUTE_SHIELD
STAT_RELATIVE_SHIELD = Entity.STAT_RELATIVE_SHIELD
STAT_RESISTANCE = Entity.STAT_RESISTANCE
STAT_SCIENCE = Entity.STAT_SCIENCE
STAT_MAGIC = Entity.STAT_MAGIC
STAT_DAMAGE_RETURN = Entity.STAT_DAMAGE_RETURN
STAT_POWER = Entity.STAT_POWER
STAT_CORES = Entity.STAT_CORES
STAT_RAM = Entity.STAT_RAM
